//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Obligatorio2Entities : DbContext
    {
        public Obligatorio2Entities()
            : base("name=Obligatorio2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mensajes> Mensajes { get; set; }
        public virtual DbSet<TipoMensaje> TipoMensaje { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual int BajaUsuario(string nomUsu, Nullable<int> ret)
        {
            var nomUsuParameter = nomUsu != null ?
                new ObjectParameter("nomUsu", nomUsu) :
                new ObjectParameter("nomUsu", typeof(string));
    
            var retParameter = ret.HasValue ?
                new ObjectParameter("ret", ret) :
                new ObjectParameter("ret", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BajaUsuario", nomUsuParameter, retParameter);
        }
    }
}
