//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mensajes()
        {
            this.UsuariosReciben = new HashSet<Usuarios>();
        }
    
        public int Codigo { get; set; }
        public string Texto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Asunto { get; set; }
        public System.DateTime Caducidad { get; set; }
        public string CodigoTipo { get; set; }
        public string NombreUsuRemitente { get; set; }
    
        public virtual TipoMensaje TipoMensaje { get; set; }
        public virtual Usuarios UsuariosEnv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual HashSet<Usuarios> UsuariosReciben { get; set; }
    }
}
